title: Fully Digital
email: info@fullydigital.se
description: > 
  Fully Digital - This site is under construction.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fullydigital.github.io" # the base hostname & protocol for your site
twitter_username: fullyflared_se
github_username:  fullydigital


markdown: kramdown
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

collections:
  case:
    output: true
    permalink: /:collection/:title/
  curious-about:
    output: true
    permalink: /:collection/:title/