# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fully Digital
email: info@fullydigital.se
description: > 
  Fully Digital - This site is under construction.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://fullydigital.se" # the base hostname & protocol for your site
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: fullyflared_se
github_username:  fullydigital

# Build settings
markdown: kramdown

collections:
  case:
    output: true
    permalink: /cases/:path/